"""
SMTP email sender for earnings briefs and digests.
"""
from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = os.getenv("SMTP_HOST", "localhost")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_ADDRESS = SMTP_USER or "noreply@earningintel.local"


def _send_email(to_emails: List[str], subject: str, body: str) -> None:
    """Low-level SMTP sender."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = FROM_ADDRESS
    msg["To"] = ", ".join(to_emails)
    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        if SMTP_PORT != 25:
            server.starttls()
        if SMTP_USER and SMTP_PASSWORD:
            server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(FROM_ADDRESS, to_emails, msg.as_string())


def send_pre_brief_email(
    to_emails: List[str],
    company_name: str,
    ticker: str,
    fiscal_period: str,
    pre_brief_data: Dict[str, Any],
) -> None:
    """Send a pre-earnings brief email."""
    subject = f"[EarningIntel] Pre-Brief: {ticker} {fiscal_period}"

    consensus_summary = pre_brief_data.get("consensus_summary", "N/A")
    revenue_est = pre_brief_data.get("revenue_est")
    eps_est = pre_brief_data.get("eps_est")
    key_watch = pre_brief_data.get("key_watch_items", [])
    prior_context = pre_brief_data.get("prior_quarter_context", "N/A")
    guidance_context = pre_brief_data.get("guidance_context", "N/A")
    bull_case = pre_brief_data.get("bull_case", "N/A")
    bear_case = pre_brief_data.get("bear_case", "N/A")
    custom_kpis = pre_brief_data.get("custom_kpis_est", {})

    watch_lines = "\n".join(f"  • {item}" for item in key_watch) if key_watch else "  N/A"
    kpi_lines = (
        "\n".join(f"  {k}: {v}" for k, v in custom_kpis.items() if v is not None)
        if custom_kpis
        else "  N/A"
    )

    body = f"""
EARNINGS INTELLIGENCE PLATFORM
Pre-Earnings Brief
{'=' * 50}

Company:        {company_name} ({ticker})
Fiscal Period:  {fiscal_period}

CONSENSUS SUMMARY
-----------------
{consensus_summary}

KEY ESTIMATES
-------------
Revenue Estimate:  {revenue_est}
EPS Estimate:      {eps_est}

KEY WATCH ITEMS
---------------
{watch_lines}

PRIOR QUARTER CONTEXT
---------------------
{prior_context}

MANAGEMENT GUIDANCE
-------------------
{guidance_context}

BULL CASE
---------
{bull_case}

BEAR CASE
---------
{bear_case}

CUSTOM KPI ESTIMATES
--------------------
{kpi_lines}

{'=' * 50}
Generated by EarningIntel
"""
    _send_email(to_emails, subject, body.strip())


def send_post_brief_email(
    to_emails: List[str],
    company_name: str,
    ticker: str,
    fiscal_period: str,
    earnings_data: Dict[str, Any],
) -> None:
    """Send a post-earnings brief email."""
    subject = f"[EarningIntel] Results: {ticker} {fiscal_period} — {earnings_data.get('beat_miss', 'N/A').upper()}"

    beat_miss = earnings_data.get("beat_miss", "N/A")
    rev_actual = earnings_data.get("revenue_actual")
    rev_est = earnings_data.get("revenue_est")
    rev_surp = earnings_data.get("revenue_surprise_pct")
    eps_actual = earnings_data.get("eps_actual")
    eps_est = earnings_data.get("eps_est")
    eps_surp = earnings_data.get("eps_surprise_pct")
    mgmt_tone = earnings_data.get("mgmt_tone", "N/A")
    guidance_tone = earnings_data.get("guidance_tone", "N/A")
    post_brief = earnings_data.get("post_brief", "N/A")
    highlights = earnings_data.get("key_highlights", [])
    red_flags = earnings_data.get("red_flags", [])
    custom_kpis = earnings_data.get("custom_kpis", {})

    highlight_lines = "\n".join(f"  • {h}" for h in highlights) if highlights else "  N/A"
    red_flag_lines = "\n".join(f"  ⚠ {f}" for f in red_flags) if red_flags else "  None identified."
    kpi_lines = (
        "\n".join(f"  {k}: {v}" for k, v in custom_kpis.items() if v is not None)
        if custom_kpis
        else "  N/A"
    )

    body = f"""
EARNINGS INTELLIGENCE PLATFORM
Post-Earnings Brief
{'=' * 50}

Company:        {company_name} ({ticker})
Fiscal Period:  {fiscal_period}
Verdict:        {beat_miss.upper() if beat_miss else 'N/A'}

FINANCIALS
----------
Revenue:  {rev_actual} (est. {rev_est}) | Surprise: {rev_surp:+.2f}% {(f'({rev_surp:+.2f}%)' if rev_surp is not None else '')}
EPS:      {eps_actual} (est. {eps_est}) | Surprise: {eps_surp:+.2f}% {(f'({eps_surp:+.2f}%)' if eps_surp is not None else '')}

Management Tone:  {mgmt_tone}
Guidance Tone:    {guidance_tone}

BRIEF
-----
{post_brief}

KEY HIGHLIGHTS
--------------
{highlight_lines}

RED FLAGS
---------
{red_flag_lines}

CUSTOM KPIS
-----------
{kpi_lines}

{'=' * 50}
Generated by EarningIntel
"""
    _send_email(to_emails, subject, body.strip())


def send_weekly_digest_email(
    to_emails: List[str],
    earnings_list: List[Dict[str, Any]],
) -> None:
    """Send a weekly earnings digest email."""
    subject = "[EarningIntel] Weekly Earnings Digest"

    if not earnings_list:
        body = "No earnings reported in the past week.\n\nGenerated by EarningIntel"
        _send_email(to_emails, subject, body)
        return

    beats = [e for e in earnings_list if e.get("beat_miss") == "beat"]
    misses = [e for e in earnings_list if e.get("beat_miss") == "miss"]
    in_line = [e for e in earnings_list if e.get("beat_miss") == "in_line"]

    rows = []
    for e in earnings_list:
        ticker = e.get("ticker", "N/A")
        period = e.get("fiscal_period", "N/A")
        verdict = (e.get("beat_miss") or "N/A").upper()
        eps_surp = e.get("eps_surprise_pct")
        surp_str = f"{eps_surp:+.2f}%" if eps_surp is not None else "N/A"
        rows.append(f"  {ticker:<8} {period:<10} {verdict:<10} EPS Surprise: {surp_str}")

    company_lines = "\n".join(rows)

    body = f"""
EARNINGS INTELLIGENCE PLATFORM
Weekly Earnings Digest
{'=' * 50}

SUMMARY
-------
Total Reports:  {len(earnings_list)}
Beats:          {len(beats)}
Misses:         {len(misses)}
In Line:        {len(in_line)}

INDIVIDUAL RESULTS
------------------
{company_lines}

{'=' * 50}
Generated by EarningIntel
"""
    _send_email(to_emails, subject, body.strip())
